### ISSUE TITLE
我在香橙派3b上安装后没有root账户是怎么回事呢

### ISSUE THREAD

**Issue by DemonYibao** [yrzr/gitlab-ce-arm64v8-docker#3]
我重新安装了另一个gitlab的arm镜像之后是正常的，zengxs的docker镜像好像是

**Comment by yrzr** [comment]
第一次启动的时候会随机生成一个root密码，存在容器内的`/etc/gitlab`文件夹下，重启后会被删掉

或者你看我给的示例里的`--env GITLAB_ROOT_PASSWORD="YourPasswordHere"`，这个只有初始化第一次运行时有用，或者你可以把整个volume删了重新来一遍

**Comment by DemonYibao** [comment]
> 第一次启动的时候会随机生成一个root密码，存在容器内的`/etc/gitlab`文件夹下，重启后会被删掉
> 
> 或者你看我给的示例里的`--env GITLAB_ROOT_PASSWORD="YourPasswordHere"`，这个只有初始化第一次运行时有用，或者你可以把整个volume删了重新来一遍

这些操作我都做过，root密码我找到了的，但是实际的问题是我在容器里面去找了root账户，提示的是没有root账户，User.find(1)没有结果

**Comment by yrzr** [comment]
所以具体情况是怎么样的呢？

我试了一下没问题啊

```bash
root@git:/# gitlab-rails console
user = User.find(1)
--------------------------------------------------------------------------------
 Ruby:         ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [aarch64-linux]
 GitLab:       16.6.1 (21d8cc00343) FOSS
 GitLab Shell: 14.30.0
 PostgreSQL:   13.12
------------------------------------------------------------[ booted in 53.46s ]
Loading production environment (Rails 7.0.8)
irb(main):001:0> user = User.find(1)
=> #<User id:1 @root>
irb(main):002:0>
```

**Comment by DemonYibao** [comment]
> 所以具体情况是怎么样

啊这，难道是我的环境问题？我重装了几次都是没有root账户，离谱离谱。而且我在未注册的情况下找root账户提示的是nil还是cil来着，然后我注册了一个之后就再去执行这个命令，提示找到的用户就是我刚刚注册的用户，并没有root
